# Generated by Django 4.2.7 on 2023-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_alter_comments_author_of_call_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=32, verbose_name='Название категории'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
